# Generated by Django 2.1.1 on 2018-09-17 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='False', max_length=50)),
                ('description', models.TextField(blank='False')),
                ('size', models.CharField(blank='False', max_length=20)),
                ('price', models.DecimalField(blank='False', decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank='False', upload_to='img')),
                ('fully_paid', models.BooleanField()),
                ('status', models.CharField(blank='False', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
