# Generated by Django 2.1.1 on 2018-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='status',
        ),
        migrations.AddField(
            model_name='commission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commission',
            name='fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commission',
            name='image',
            field=models.FileField(upload_to='media/commissions'),
        ),
    ]
