# Generated by Django 2.1.1 on 2018-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_auto_20180924_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='deposit_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='fully_paid_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commission',
            name='proposed_date',
            field=models.DateField(null=True),
        ),
    ]
