# Generated by Django 2.1.1 on 2018-09-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_auto_20180924_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='price',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10),
        ),
    ]
