# Generated by Django 2.1.1 on 2018-10-01 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0005_auto_20180924_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/commissions')),
                ('comments', models.TextField(blank='False', null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='commission',
            name='fully_paid_date',
        ),
        migrations.AlterField(
            model_name='commission',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commission.Commission'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
