# Generated by Django 2.1.1 on 2018-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_auto_20181001_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.FileField(null=True, upload_to='media/commissions'),
        ),
    ]
