# Generated by Django 2.1.1 on 2018-09-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prints',
            new_name='Print',
        ),
    ]
