# Generated by Django 2.1.1 on 2018-09-17 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prints', '0002_auto_20180909_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original',
            fields=[
                ('print_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prints.Print')),
                ('highest_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            bases=('prints.print',),
        ),
    ]
