# Generated by Django 2.1.1 on 2018-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20180920_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='paid',
            field=models.BooleanField(default='False'),
        ),
    ]
