# Generated by Django 2.1.1 on 2018-09-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prints', '0002_auto_20180909_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank='False', max_length=50)),
                ('address_line1', models.CharField(blank='False', max_length=100)),
                ('address_line2', models.CharField(blank='True', max_length=100)),
                ('county', models.CharField(blank='False', max_length=30)),
                ('postcode', models.CharField(blank='True', max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank='False')),
                ('order', models.ForeignKey(null='False', on_delete=django.db.models.deletion.PROTECT, to='checkout.Order')),
                ('product', models.ForeignKey(null='False', on_delete=django.db.models.deletion.PROTECT, to='prints.Print')),
            ],
        ),
    ]
